### ISSUE TITLE
Unable to add ENVs for booleans that have a false value in the example json

### ISSUE THREAD

**Issue by jpantarotto** [Strider-CD/strider-metadata#3]
I was unable to add the variable 'errored' as an ENV because the falsy value doesn't pass the angular isValid() test for the example (e.g. in the example json the value is false).  I resorted to updating the config in the database as a workaround.  Has anyone else experienced this?  I experienced the issue in Chrome Version 56.0.2924.87, Safari Version 10.0.3 (12602.4.8), and Firefox 51.0.1.  I also tried adding other configs that were false and was unable to do so.

**Comment by knownasilya** [comment]
Envs always come across as strings, so you must test for the string value of `'false'`.

**Comment by jpantarotto** [comment]
Are you saying I should somehow test the value in the UI or was that a suggestion for improvement?  My issue is that I cannot set an ENV for a boolean valued job metadata item if the value in the example json is false

**Comment by knownasilya** [comment]
It's just how environment variables work, your app needs to account for it.

**Comment by jpantarotto** [comment]
I think you're misunderstanding my issue.  When I try to expose the job metadata variable "errored" the green "Add" button does not appear.  However, if I try to expose a boolean metadata value that is truthy, I'm able to add the ENV.  Please see attached images
![screen shot 2017-02-28 at 1 45 19 pm](https://cloud.githubusercontent.com/assets/3589149/23435463/6b1addc2-fdbc-11e6-915a-8c17f30d87fb.png)
![screen shot 2017-02-28 at 1 45 56 pm](https://cloud.githubusercontent.com/assets/3589149/23435476/716d3d0a-fdbc-11e6-8146-12ee538ac087.png)

**Comment by knownasilya** [comment]
Ah, yes, that's a bug.

**Comment by caizx666** [comment]
Fix:  https://github.com/Strider-CD/strider-metadata/pull/4
